### ISSUE TITLE
NoCheatPlus finds the "round finished" tp to be "survival flying"

### ISSUE THREAD

**Issue by GamersCorp** [aarontwf/BattleNight-Core#91]
Hi there,

I'm using the latest build of Battlenight, 1.6. Whenever a round ends, the players are automatically tp'd out of the arena, or are supposed to, anyways. However, NoCheatPlus finds this tp as "survivalfly", with very high violation levels, and all my players are autokicked from the server due to that. I'm not sure if I should be posting this here, or at NoCheatPlus's github, but I thought I'd put it here anyways.

Thanks.

**Comment by Pancakebang** [comment]
I have the same problem! Thanks for mentioning it.

**Comment by server075** [comment]
Still no fix, ill post the same:  

Whenever a round ends, the players are automatically tp'd out of the arena, or are supposed to, anyways. However, NoCheatPlus finds this tp as "survivalfly", with very high violation levels, and all my players are autokicked from the server due to that.

How ever i removed it in NoCheat+ (atm) so we can still play Battlenight.

**Comment by server075** [comment]
Pancakebang  commented 4 months ago  o_O

**Comment by aarontwf** [comment]
Fixed in v1.9.0
